// Usuarios:
export const GET_USUARIOS_BEGIN = "GET_USUARIOS_BEGIN";
export const GET_USUARIOS_SUCCESS = "GET_USUARIOS_SUCCESS";
export const GET_USUARIOS_ERROR = "GET_USUARIOS_ERROR";
// Open Forms:
export const OPEN_ADD_EMP_FORM = "OPEN_ADD_EMP_FORM";
export const CLOSE_ADD_EMP_FORM = "CLOSE_ADD_EMP_FORM";
